### ISSUE TITLE
Session in load balancer environment.

### ISSUE THREAD

**Issue by zeyab** [btmorex/hapi-server-session#13]
Is the session tied to single server? Or is the session supported in non-sticky load balancer environment?

**Comment by btmorex** [comment]
The session is tied to the hapi cache which defaults to a temporary, in-memory store. So by default session is tied to the particular node.js process, but if you change the hapi cache configuration to say memcache or redis you can share amongst servers behind a load balancer.

**Comment by zeyab** [comment]
Great! Thanks. That is what I wanted to confirm.
