### ISSUE TITLE
How to keep session alive

### ISSUE THREAD

**Issue by francistm** [btmorex/hapi-server-session#5]
At current version, Session could only survive to the ttl, even access a route, or set new value.

Is there any possible to extend the ttl for session after access the routes?

Thanks.

**Comment by btmorex** [comment]
Can you explain your use case a little bit? And are you referring to the ttl of the cookie or of the server side cache?

**Comment by btmorex** [comment]
Fixed in a6ec5bf056c4e49f7dfe1ac584b5c2aaceedef25
