### ISSUE TITLE
Destroying sessions

### ISSUE THREAD

**Issue by hsablonniere** [btmorex/hapi-server-session#8]
Hey @btmorex :smile:

I'm trying to use your plugin to manage authentication. I stored the authenticated `userId` in the session.

When the user logs out, I want to destroy the cookie client-side and to destroy the session server side.

I was expecting a helper to delete the cookie but it seems I need to call this myself:

```
h.unstate(cookieName);
```

I also noticed that I have no access to the cache to properly clear/invalidate my session.
I know I can just do this:

```
request.session = {}
```

but I would prefer to delete it entirely.

Questions:

1. Are you interested in adding a way to delete the cookie?
2. Are you interested in adding a way to destroy the session from the cache?

I can help and provide propositions through PRs but I wanted to have your approval, advices and guidance before :wink: 

Cheers,
Hubert

**Comment by hsablonniere** [comment]
Something like this:

```js
const storeSession = async (request, h) => {
  if (hoek.deepEqual(request.session, request._session)) {
    return h.continue;
  }
  let sessionId = request._sessionId;
  if (!sessionId) {
    sessionId = createSessionId();
    h.state(options.name, sessionId);
  }

  // If session is null, we destroy is client side and server side
  if (request.session == null) {
    await cache.drop(sessionId);
    h.unstate(options.name);
    return h.continue;
  }

  await cache.set(sessionId, request.session, 0);
  return h.continue;
};
```

The user of the plugin would just have to do this in a logout route:

```js
async handler (request, h) {
  request.session = null
  return h.redirect('/')
},
```

**Comment by btmorex** [comment]
Sorry @hsablonniere, I saw this a while ago and was going to reply immediately, but got wrapped up in other things.

I originally had planned on implementing similar functionality, but just never got around to it. Setting session to null seems reasonable as an api, but it's a breaking change so I'd like to think about it a little more.

**Comment by btmorex** [comment]
Sorry for being slow! I think I would be perfectly fine with

```javascript
delete request.session;
```

deleting the cookie and clearing the cache. In other words, delete everything if session is undefined. Right now, I don't think null sessions can be stored in catbox, but in the future I might change it so that all JSON serializable data is allowed in which case null would be a valid value. I'd welcome a pull request in any case.

**Comment by hsablonniere** [comment]
@btmorex I was off my hapi.js for a while, so sorry for the late comment but thanks very much for this ;-)
