### ISSUE TITLE
Reset session timeout in every request

### ISSUE THREAD

**Issue by miljosh68** [btmorex/hapi-server-session#9]
Pardon me if there is way to do it already. I am new to Node/Hapi and do not know how to accomplish it. 

My environment is: 
node: 10.7.0
hapi: 17.5.3
hapi-server-session: 4.4.2

I am using hapi-server-session and have currently set the session timeout at 3 minutes, using the following code, 
```
await server.register({
        plugin: require('hapi-server-session'),
        options: {
            cookie: {
                isSecure: false, 
                isHttpOnly: true,
                encoding: 'base64json',
            }, 
            name: 'myCookieName',
            expiresIn: 3 * 60 * 1000 // session expires in 3 minutes
        }
    });
```
Actually when the user moves from one page to another page, I want to reset the timeout. That way, essentially, if the user has done nothing in 3 minutes the session should timeout, but, if the user performed an action say after 2 minutes 55 seconds and clicked on a button to retrieve data. I want that action to set the timeout to 3 minutes so that the session times out after 3 minutes of inactivity and not 5 seconds.

**Comment by btmorex** [comment]
Typically this behavior is called rolling sessions and unfortunately there's currently no way to do this with hapi-server-session. Definitely on the list and I'd welcome a contribution.

**Comment by btmorex** [comment]
Check out #11 if you want

I'm not happy enough with the implementation to merge. It should be more comprehensive in terms of other options used and should have better tests, but it should also work for you.
